project_id = "mefiixczdxprchjvvwlr"

[functions.customer-chat]
verify_jwt = false

[functions.send-inquiry-email]
verify_jwt = false

[functions.provision-admin]
verify_jwt = false

[functions.ncba-payment]
verify_jwt = false